// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm5G_Yj7FYF9kLJwjGq7VWa3Om2dRTVpk',
    appId: '1:1010043216183:web:846d3d6f9e944e44087ab2',
    messagingSenderId: '1010043216183',
    projectId: 'individual-project2-e2931',
    authDomain: 'individual-project2-e2931.firebaseapp.com',
    storageBucket: 'individual-project2-e2931.firebasestorage.app',
    measurementId: 'G-RNQFEHGZQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiyedBaQ5WG330PyKHPkBOdIz2FfNgtNg',
    appId: '1:1010043216183:android:8c0c23eed752cfc6087ab2',
    messagingSenderId: '1010043216183',
    projectId: 'individual-project2-e2931',
    storageBucket: 'individual-project2-e2931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrSPr-9p99n4p_kxp5NsviovTcYjm7MU',
    appId: '1:1010043216183:ios:62cdd29067299a95087ab2',
    messagingSenderId: '1010043216183',
    projectId: 'individual-project2-e2931',
    storageBucket: 'individual-project2-e2931.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIrSPr-9p99n4p_kxp5NsviovTcYjm7MU',
    appId: '1:1010043216183:ios:62cdd29067299a95087ab2',
    messagingSenderId: '1010043216183',
    projectId: 'individual-project2-e2931',
    storageBucket: 'individual-project2-e2931.firebasestorage.app',
    iosBundleId: 'com.example.individualAssignment2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm5G_Yj7FYF9kLJwjGq7VWa3Om2dRTVpk',
    appId: '1:1010043216183:web:958db6d2239c8733087ab2',
    messagingSenderId: '1010043216183',
    projectId: 'individual-project2-e2931',
    authDomain: 'individual-project2-e2931.firebaseapp.com',
    storageBucket: 'individual-project2-e2931.firebasestorage.app',
    measurementId: 'G-9K6T3MGQ7M',
  );
}
